import { defineField, defineType, defineArrayMember } from 'sanity'
import { PresentationIcon } from '@sanity/icons'

export const caseStudy = defineType({
  name: 'caseStudy',
  title: 'Case Study',
  type: 'document',
  icon: PresentationIcon,
  groups: [
    { name: 'company', title: 'Company', default: true },
    { name: 'content', title: 'Content' },
    { name: 'metrics', title: 'Metrics' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'company',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'company',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'companyName',
      title: 'Company Name',
      type: 'string',
      group: 'company',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'logo',
      title: 'Company Logo',
      type: 'image',
      group: 'company',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'industry',
      title: 'Industry',
      type: 'string',
      group: 'company',
    }),
    defineField({
      name: 'companySize',
      title: 'Company Size',
      type: 'string',
      group: 'company',
      description: 'e.g. "50-200 employees", "Enterprise"',
    }),
    defineField({
      name: 'platformsUsed',
      title: 'Platforms Used',
      type: 'array',
      group: 'company',
      of: [defineArrayMember({ type: 'string' })],
      options: {
        list: [
          { title: 'Instagram', value: 'instagram' },
          { title: 'Twitter / X', value: 'twitter' },
          { title: 'LinkedIn', value: 'linkedin' },
          { title: 'Facebook', value: 'facebook' },
          { title: 'TikTok', value: 'tiktok' },
          { title: 'YouTube', value: 'youtube' },
          { title: 'Pinterest', value: 'pinterest' },
          { title: 'Threads', value: 'threads' },
        ],
      },
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      group: 'company',
      initialValue: false,
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      group: 'company',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'challenge',
      title: 'Challenge',
      type: 'array',
      group: 'content',
      of: [
        defineArrayMember({
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H3', value: 'h3' },
          ],
        }),
        defineArrayMember({ type: 'pteImage' }),
        defineArrayMember({ type: 'pteCallout' }),
        defineArrayMember({ type: 'pteCode' }),
      ],
    }),
    defineField({
      name: 'solution',
      title: 'Solution',
      type: 'array',
      group: 'content',
      of: [
        defineArrayMember({
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H3', value: 'h3' },
          ],
        }),
        defineArrayMember({ type: 'pteImage' }),
        defineArrayMember({ type: 'pteCallout' }),
        defineArrayMember({ type: 'pteCode' }),
      ],
    }),
    defineField({
      name: 'results',
      title: 'Results',
      type: 'array',
      group: 'content',
      of: [
        defineArrayMember({
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H3', value: 'h3' },
          ],
        }),
        defineArrayMember({ type: 'pteImage' }),
        defineArrayMember({ type: 'pteCallout' }),
        defineArrayMember({ type: 'pteCode' }),
      ],
    }),
    defineField({
      name: 'metrics',
      title: 'Key Metrics',
      type: 'array',
      group: 'metrics',
      of: [defineArrayMember({ type: 'metric' })],
    }),
    defineField({
      name: 'testimonial',
      title: 'Testimonial',
      type: 'reference',
      group: 'content',
      to: [{ type: 'testimonial' }],
      description: 'Link to an existing testimonial document',
    }),
    defineField({
      name: 'testimonialQuote',
      title: 'Testimonial Quote (Legacy)',
      type: 'text',
      group: 'content',
      rows: 3,
      description: 'Use the testimonial reference above instead',
      deprecated: { reason: 'Use the testimonial reference field instead' },
      hidden: ({ value }: { value: unknown }) => value === undefined,
      readOnly: true,
    }),
    defineField({
      name: 'testimonialAuthor',
      title: 'Testimonial Author (Legacy)',
      type: 'string',
      group: 'content',
      deprecated: { reason: 'Use the testimonial reference field instead' },
      hidden: ({ value }: { value: unknown }) => value === undefined,
      readOnly: true,
    }),
    defineField({
      name: 'testimonialRole',
      title: 'Testimonial Role (Legacy)',
      type: 'string',
      group: 'content',
      deprecated: { reason: 'Use the testimonial reference field instead' },
      hidden: ({ value }: { value: unknown }) => value === undefined,
      readOnly: true,
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'companyName',
      media: 'logo',
    },
  },
})
